name: Deploy Laravel to Local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy project
        run: |
          echo "Starting deployment..."

          cd C:\xampp\htdocs

          if not exist wingoo (
            git clone https://github.com/Vishakarex/winngoo-pm-backend wingoo
          )

          cd wingoo

          git pull origin main

          echo "Installing dependencies..."
          C:\xampp\php\php C:\composer\composer.phar install --no-interaction --prefer-dist --optimize-autoloader

          echo "Running Laravel commands..."
          C:\xampp\php\php artisan migrate --force
          C:\xampp\php\php artisan config:cache
          C:\xampp\php\php artisan route:cache
          C:\xampp\php\php artisan view:cache

          echo "Deployment completed successfully!"
